// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnzBeOcMf8swsyG2s-FOZnDtwz945OljI',
    appId: '1:534541293392:web:64c02ba19f3094a8bb3e55',
    messagingSenderId: '534541293392',
    projectId: 'push-notifications-58bae',
    authDomain: 'push-notifications-58bae.firebaseapp.com',
    storageBucket: 'push-notifications-58bae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8bJKIsjPbYNfLxquu9V0uBQpYJTNh6ms',
    appId: '1:534541293392:android:54e22c1a82d5be1bbb3e55',
    messagingSenderId: '534541293392',
    projectId: 'push-notifications-58bae',
    storageBucket: 'push-notifications-58bae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6RriYE5PNcA4Q8vcpX4nP6Rbs5ap0NUw',
    appId: '1:534541293392:ios:db93cf6dffd34c16bb3e55',
    messagingSenderId: '534541293392',
    projectId: 'push-notifications-58bae',
    storageBucket: 'push-notifications-58bae.appspot.com',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6RriYE5PNcA4Q8vcpX4nP6Rbs5ap0NUw',
    appId: '1:534541293392:ios:db93cf6dffd34c16bb3e55',
    messagingSenderId: '534541293392',
    projectId: 'push-notifications-58bae',
    storageBucket: 'push-notifications-58bae.appspot.com',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnzBeOcMf8swsyG2s-FOZnDtwz945OljI',
    appId: '1:534541293392:web:b160c80a5cc404f7bb3e55',
    messagingSenderId: '534541293392',
    projectId: 'push-notifications-58bae',
    authDomain: 'push-notifications-58bae.firebaseapp.com',
    storageBucket: 'push-notifications-58bae.appspot.com',
  );
}
